- src/os2.cc
In my build on OS X (with clang), this fails with "error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]". (Adding the spaces improves readability, IMO, in addition to fixing the build failure.)
> Fix for C++11 compilation failure

- include/opentype-sanitiser.h
- src/cmap.cc
In cmap.cc, ots_cmap_serialise() may seek the output stream to a random
position in the table when it constructs UVS tables. But those seeks
didn't care about checksum calculation state of OTSStream, so it could
lead to an assertion failure in OTSStream::chksum().
After this patch, OTSStream::Write() simply accumulates checksum values
for incomplete words. As a result, it no longer needs to keep hanging
bytes.
> Make checksum calculation more resilient against stream seek

- src/ots.cc
Visual Studio does not support variable length arrays.
> Fix windows build

- docs/HowToFix.md
I'd like to document this information kindly gathered by Nicolas on the DFLT script font error that has come up recently.
> Includ a docs/HowToFix.md file

- src/cmap.cc
Since mutiplying numbers cannot detect all overflows.
> Update overflow checks in src/cmap.cc

- src/ots.cc
This is for issue #108. 
See also http://crbug.com/605334 and https://codereview.chromium.org/1911123002
> Do not reject a sbix font without loca/glyf tables.

- src/gloc.cc
- src/silf.cc
Follow-up to #134 - Perform most checks when parsing but perform checks specifically intended to protect arithmetic operations immediately before the operation
> [graphite] Make overflow checking consistent

- src/feat.cc
- src/glat.cc
- src/gloc.cc
- src/sile.cc
- src/silf.cc
- src/sill.cc
Reduces memory usage when parsing some bad fonts.
> [graphite] Replace std::vector::resize with std::vector::emplace_back

- src/feat.cc
- src/sill.cc
Better performance. (Fuzz testcase 4559306173186048: 801 ms → 11 ms.)
> [graphite] Reject unreasonable FeatSettingDefn and LangFeatureSetting offsets earlier

- src/glat.cc
Silences compiler warnings during Firefox compilation. (Ultimately, GlatEntry::num should be changed to an unsigned value in the Graphite spec.)
> [graphite] Match signedness in GlatEntry loop

- src/silf.cc
- src/sill.cc
The correct values for these fields can be computed from the number of entries
in the list to be searched, so we can simply overwrite them with the proper
values rather than rejecting tables where they appear wrong.
(Existing fonts in circulation often have bad values in these fields; in
practice, it doesn't matter because the current engine does not rely on
them, and therefore the errors have not been noticed. But in case any future
engine does try to use them, we should fix them up here.)
> [graphite] Fix binary-search header fields rather than dropping table

- src/silf.cc
This field is only used by the Graphite justifier, which no client applications are
currently (known to be) using. The value in Awami (at least) is incorrect due to a
bug in the subsetter being used to generate the font served on the Graphite demo page,
but as it is unused, the error is harmless and we shouldn't reject the font.
Setting to zero should be benign; at worst, I guess a client that did attempt to use the
justifier might see spurious .notdef glyphs, but there should be no security issues
as a result.
> [graphite] Fix invalid lbGID instead of dropping table

- docs/HowToTest.md
I verified locally that the currently-recommended command, `make ckeck`, is unrecognized, whereas the corrected `make check` command *does* actually run the tests. :)
> Fix typo in HowToTest.md (s/ckeck/check/)

- src/layout.cc
As used in place of Device Tables in fonts with variation axes. This is a trivial fix to allow such a GPOS table to be parsed, rather than rejected for an invalid device table format.
> Don't reject variation fonts for having a VariationIndex table

- src/stat.cc
- src/variations.cc
These are straightforward fixes: a missing offset check before calling a parsing function, and a few cases where offset/length computations using 16-bit fields might overflow (so we need to explicitly promote the values to at least 32-bit before doing arithmetic with them).
> Fix issues found by ots-fuzzer

- src/stat.h
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=7361
and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=7372
> [STAT] Must properly construct vector<> before assigning to it.

- src/fvar.h
- src/gvar.cc
- src/hvar.cc
- src/mvar.cc
- src/stat.h
- src/variations.cc
- src/vvar.cc
This just cleans up a few things that result in warnings during the Firefox build.
> Clean up some compiler warnings.

- src/glyf.cc
When maxp.maxSizeOfInstructions and the bytecode mismatch, fix the former and warn instead of rejecting the font.
Fixes https://github.com/khaledhosny/ots/issues/181
> [glyf] Fix miscalculated maxp.maxSizeOfInstructions

- src/stat.cc
Coverity is worried that `name` could be nullptr here (as `GetTypedTable` can return null). This won't actually happen, because `name` is a required table and so OTS will reject the font before it even attempts to parse `STAT` if it is missing; but I suggest we add a null-check here rather than relying on the order of table processing.
> [STAT] Add null-check to silence coverity warning

- src/variations.cc
This variable has no usages (and doesn't seem to have had any usages in the commit that added it, https://github.com/khaledhosny/ots/commit/5ae961372b0c1709f756144f0053d0a69874b794 ).
It causes a `-Wunused-variable` build warning, so let's remove it.
> Remove unused variable INNER_INDEX_BIT_COUNT_MASK

- src/variations.cc
OTS enforces that VarStore.VarRegionList.RegionAxisCount be always equal to the fvar.axisCount, even when the VarRegionList is empty and contains no regions.
When fonttools compiles empty VarRegionList containing no VarRegions, the RegionAxisCount defaults to 0, instead of always be equal to fvar.axisCount. This is because the count value is dynamically propagated from the length of the VarRegion.VarRegionAxis array.
@behdad argued that it should be allowed to have RegionAxisCount == 0 when the VarRegionList is empty. This PR changes OTS so that it checks VarRegionList.RegionAxisCount == fvar.axisCount only when there are any regions in the list, otherwise ignore the value.
Related issues:
https://github.com/googlefonts/fontmake/issues/565
https://github.com/fonttools/fonttools/pull/1671 …
> [variations] allow VarRegionList.RegionAxisCount be 0 when RegionCount is 0

- src/silf.cc
With reference to #196 this PR removes version dependent checks that reserved values that were given a meaning in a later version of the table specification, may only take such a value if the Silf table is of a version greater or equal to the version of the specification in which the reserved value was given the meaning. This is in response to a change in the GTF specification that says:
> Notice that reserved values do not have to be 0. In addition, some values that were transitioned from reserved to having a meaning, may also be used in Silf tables whose version number is lower than the version in which the meaning was introduced.
I have still left in the checks that currently reserved values are 0. These may be removed at a later date or when the reserved values are given meaning. …
> Remove version dependent reserved value checks from silf

- src/cmap.cc
This will fix the issue that: 
when both defaultUVSOffset and nonDefaultUVSOffset are non-zero and default UVS table has a larger offset value than non-default one, subtable.offset() is incorrectly set by the non default UVS table
> cmap14 table fix:

- src/gsub.cc
It doesn't make sense to check component_count against num_glyphs; if a component glyph is repeated within the ligature sequence, the count could legitimately be greater than the number of distinct glyphs in the font. See https://bugzilla.mozilla.org/show_bug.cgi?id=1634834.
(Also fixed a few trivial typos in messages that caught my eye.)
> Remove spurious component_count check

- src/ots.cc
This doesn't need to be a validation failure, we can just warn and fix the value, like we do for other searchHeader fields.
> Fixup bad entry_selector in the table directory

- src/feat.h
- src/silf.cc
- src/silf.h
Three fixes for Graphite tables:
1. correct spelling `attCollisions` -> `attrCollisions`
2. `attrCollisions` was introduced in Silf table version 4.1, not 5.0
3. The 0x800 bit is now defined and used in the FeatureDefn flags
Thanks
> Graphite fixes

- meson.build
Needed for https://github.com/google/oss-fuzz/pull/4089
I followed the nice approach here for integrating oss-fuzz into the project and faced with https://github.com/google/oss-fuzz/pull/4076#discussion_r451118950 so thought should improve ots also now that it helped me :)
> [meson] split fuzzer_ldflags if isn't empty

- src/ots.cc
If the table is left in m_table it may be used by other variation handling code. Such as in GSUB ParseConditionTable.
> When dropping variation table, also remove from m_tables.

- src/glat.cc
- src/ots.cc
- src/ots.h
- src/silf.cc
- add `OTS_MAX_DECOMPRESSED_FILE_SIZE` and `OTS_MAX_DECOMPRESSED_TABLE_SIZE` constants
- replace previous limit values with those constants
- minor updates to the related failure messaging
Closes #219
> Increase limits for decompressed tables and files

- docs/ots-sanitize.1
This was presumably left over from using `yes.1` as a template.
> Fix wrong command name “yes” in SYNOPSIS section of man page ots-sanitize.1

- include/opentype-sanitiser.h
- include/ots-memory-stream.h
- src/ots.cc
- util/ots-sanitize.cc
Currently we are exiting early if decompressed size exceeds
OTS_MAX_DECOMPRESSED_FILE_SIZE=300MB but some callers may actually set a
smaller limit. For example, Chromium uses 30MB [1] and its internal
fuzzer 256kB [2]. Firefox uses a limit of 256MB [3].
[1] https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/platform/fonts/web_font_decoder.cc;l=155;drc=5863e513ede6d1f7e9a060f13635fd3916a2183c
[2] https://source.chromium.org/chromium/chromium/src/+/main:third_party/ots/fuzz/ots_fuzzer.cc;l=11;drc=efffce8e2a6da2d2295472ed24ef040e0bf4ea14
[3] https://searchfox.org/mozilla-central/rev/3e1a721bce1da3ae04675539b39a4e95b25a046d/gfx/thebes/gfxOTSUtils.h#28
> Exit early if decompressed size exceeds OTSStream's size limit

- src/glyf.cc
I have a font giving an ots warning:
```
WARNING: glyf: Bytecode length is bigger than maxp.maxSizeOfInstructions 4937: 4937
```
This confused me a little until I looked at the code. I believe the warning should be printed before the `maxp` value is updated.
> [review] Set the correct values in the max size of glyf instructions warning.

- .github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz where OTS already runs. CIFuzz can help detect regressions and catch fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.
> [ci] Add CIFuzz Github action

- util/ots-idempotent.cc
If FreeType and another platform backend is enabled, we want to prefer the platform one.
Fixes https://github.com/khaledhosny/ots/issues/254
> [util] Prefer Win32 version of VerifyTranscodedFont

- src/layout.cc
There's no reason that a glyph sequence can't exceed the number of glyphs in a font. These are sequences of glyphs and as such allow repetition of glyph ids. The current checks can cause small subsets of fonts to incorrectly fail OTS sanitization.
> Remove checks for Chain and Context rules that fail fonts for having glyph sequences that exceed the number of glyphs in the font.

- src/cff_charstring.cc
This triggers a warning we can avoid:
src/cff_charstring.cc:387:20: warning: comparison of integer expressions of different signedness: ‘const size_t’ {aka ‘const long unsigned int’} and ‘int’ [-Wsign-compare]
> Fix comparison of integer expressions of different signedness

- src/ots.cc
It it is a TTC font and we drop the variations table, we will create a new table for each face index but free only one.
> [ots] Actually fix gvar leak

- src/glyf.cc
- src/glyf.h
Fixes #263.
(Actually, only a partial fix: this only deals with simple outline glyphs, not composite glyphs. In principle we could do something with those as well, but it seems like significantly more effort and probably less likely to arise in practice.)
> Check & fix bounding box of simple glyph records.

- src/maxp.cc
- src/ots.cc
If the version number is less than 0x00010000 (e.g. an example reported at https://github.com/mozilla/pdf.js/issues/16839 apparently has 0x0100), it will be treated as version 0.5 and only the num_glyphs field is kept.
However, this can prevent the font working on Windows, which apparently requires the full version 1.0 maxp table for truetype fonts.
So if the version number was bad, but there is in fact enough data to parse as version 1.0, let's try correcting it to 1.0 rather than 0.5.
(Test not included because the example in the issue appears to be a derivative of a proprietary font.)
> [maxp] Attempt to improve fixup of bad 'maxp' version numbers.

- include/ots-memory-stream.h
Fixes a build warning on builds where off_t and size_t are different.
> Fix a size_t/off_t mismatch build warning

- src/cff.cc
This is @nagyatosz's patch from https://github.com/khaledhosny/ots/pull/269, plus a change to explicitly reject negative offsets. Although the spec does not seem to prohibit them, support in implementations is patchy, and AFAIK no mainstream tool or workflow will generate such a font. So it seems safer to reject them than to allow such an untested niche feature that implementations may mishandle.
@khaledhosny WDYT of doing something like this? We could reconsider if there's evidence of a real-world need to support this, though discussion indicated that not all engines would actually work with such a font.
> [cff] correctly parse negative operands, but don't allow -ve offset

- src/ots.cc
This pull request addresses the issue in https://github.com/khaledhosny/ots/issues/219.
The [original PR](https://github.com/khaledhosny/ots/pull/229) did not fully fix the issue of 30MB limit.
The current code still fails for fonts >30MB uncompressed when calling [woff2::ConvertWOFF2ToTTF](https://github.com/khaledhosny/ots/blob/27d63ae4d8988619e0a661bf40551c47da47f3fa/src/ots.cc#L547).
The issue is that the constructor of WOFF2StringOut [sets the maxSize](https://github.com/google/woff2/blob/0f4d304faa1c62994536dc73510305c7357da8d4/src/woff2_out.cc#L14) of the buffer to `kDefaultMaxSize`, which is also set to [30MB](https://github.com/google/woff2/blob/0f4d304faa1c62994536dc73510305c7357da8d4/include/woff2/output.h#L20)
To properly fix this, we will need to ensure the maxSize of the …
> Set correct max_size for woff2 decompress output buffer

- src/layout.cc
An improperly ordered filter range is a non-fatal error; just issue a warning.
Condition table format 1 is described at
https://learn.microsoft.com/en-gb/typography/opentype/spec/chapter2#condition-table-format-1-font-variation-axis-range
In mozilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1916037, we saw fonts being rejected due to incorrectly-ordered min/max values in this table, but this does not need to be a hard error.
> Warn rather than fail if min/max of a condition table range are reversed

- src/ots.cc
This avoids the risk of the returned message including NUL or other non-printing characters.
(See https://bugzilla.mozilla.org/show_bug.cgi?id=1937227 for the example that motivated this change.)
> Show invalid table tags as hex in error messages.

- src/os2.cc
Fixes a warning message for a bad sxHeight. 
Issue reported here: https://bugzilla.mozilla.org/show_bug.cgi?id=1937231
Reproducing the issue from the above thread:
> fix warning text for bad sxHeight
